title: 131 TA Handbook
description: A TA handbook for UCLA COM SCI 131
theme: just-the-docs


url: https://ucla-cs-131.github.io

baseurl: "/handbook"

aux_links:
  GitHub Repository: https://github.com/UCLA-CS-131/handbook

nav_external_links:
  - title: GitHub Organization
    url: https://github.com/UCLA-CS-131
  - title: Barista
    url: https://barista.fly.dev

permalink: pretty

# callouts
callouts_level: quiet # or loud
callouts:
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/UCLA-CS-131/handbook" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"
