title: 131 TA Handbook
description: A TA handbook for UCLA COM SCI 131
theme: just-the-docs


url: https://ucla-cs-131.github.io

baseurl: "/handbook"

aux_links:
  GitHub Repository: https://github.com/UCLA-CS-131/handbook
